"""System executor (PR4, task 4.4): shutdown/reboot via systemctl, open_app allowlisted, execute arbitrary commands.

Design (RF-8, threat matrix): destructive actions run behind the orchestrator's
15s confirm gate and are logged here; open_app only ever spawns xdg-open with
an allowlisted app (disallowed app => rejected, nothing spawned). The execute
intent runs arbitrary shell commands with confirmation (Option A) or auto
(Option B via AUTO_EXECUTE config).

Security: execute uses a SAFE_BINARIES allowlist + shell operator blocklist.
Only commands whose first token is an allowed binary pass through. Shell
operators (|, ;, &, >, <, $, `) are always rejected to prevent injection.
"""

from __future__ import annotations

import re
import shlex

from jarvis import config
from jarvis.actions import base
from jarvis.interpreter import schema
from jarvis.interpreter.schema import Intent
from jarvis.orchestrator.contracts import ActionResult

# User-friendly names → actual command/bin names.
# xdg-open only works with .desktop files or URLs, not app aliases.
_APP_COMMANDS: dict[str, str] = {
    "terminal": "gnome-terminal",
    "explorador": "nemo",
    "navegador": "firefox",
    "nemo": "nemo",
    "nautilus": "nautilus",
    "libreoffice": "libreoffice",
    "code": "code",
    "codium": "codium",
    "vim": "gnome-terminal",
    "nano": "gnome-terminal",
    "htop": "gnome-terminal",
    "opencode": "opencode",
    "spotify": "spotify",
}

# --- Execute security: allowlist + operator blocklist -------------------------

# Safe binaries the LLM is allowed to generate commands for.
# This is intentionally restrictive — if a command isn't here, it's rejected.
SAFE_BINARIES: frozenset[str] = frozenset({
    # file ops
    "ls", "pwd", "cd", "cat", "head", "tail", "wc", "find", "grep", "rg",
    "file", "stat", "du", "df", "tree",
    # dir ops
    "mkdir", "rmdir", "touch", "cp", "mv", "ln",
    # text
    "echo", "sort", "uniq", "tr", "cut", "sed", "awk", "xargs",
    # dev tools
    "git", "python", "python3", "pip", "pip3", "node", "npm", "npx",
    "cargo", "rustc", "go", "make", "cmake",
    # editors (open in terminal)
    "vim", "nvim", "nano", "emacs", "code", "codium",
    # system info
    "date", "whoami", "hostname", "uname", "env", "which", "type",
    "ps", "top", "htop", "free", "uptime", "lscpu",
    # archives
    "tar", "unzip", "zip", "gzip", "gunzip",
    # safe rm with restrictions (handled separately)
    "rm",
    # other safe tools
    "diff", "chmod",
})

# Shell operators that indicate injection attempts — always rejected.
_SHELL_OPERATORS = re.compile(r"[;|&$<>`\\]")

# rm restrictions: reject -rf, -fr, -r followed by -f, -f followed by -r
_RM_DANGEROUS = re.compile(r"\brm\b.*-(?:[a-zA-Z]*r[a-zA-Z]*f|f[a-zA-Z]*r)")


def _run(name: str, command: list[str], ok_spoken: str, fail_spoken: str) -> ActionResult:
    base.log(name)
    code, _ = base.safe_run(command)
    if code != 0:
        return ActionResult(ok=False, spoken=fail_spoken)
    return ActionResult(ok=True, spoken=ok_spoken)


def shutdown(intent: Intent, session: object) -> ActionResult:
    return _run("shutdown", ["systemctl", "poweroff"], "Apagando el sistema, señor.", "Lo lamento, señor, no pude apagar el sistema.")


def reboot(intent: Intent, session: object) -> ActionResult:
    return _run("reboot", ["systemctl", "reboot"], "Reiniciando el sistema, señor.", "Lo lamento, señor, no pude reiniciar el sistema.")


def open_app(intent: Intent, session: object) -> ActionResult:
    app = intent.entities.get("app", "")
    invalid = schema.validate_entities(intent, config.ALLOWED_APPS)
    if invalid:
        return ActionResult(ok=False, spoken="Esa aplicación no está permitida, señor.")
    # Resolve friendly name to actual command
    command = _APP_COMMANDS.get(app, app)
    code, _ = base.safe_run([command])
    if code != 0:
        return ActionResult(ok=False, spoken="Lo lamento, señor, no pude abrir esa aplicación.")
    return ActionResult(ok=True, spoken=f"Abriendo {app}, señor.")


def execute(intent: Intent, session: object) -> ActionResult:
    """Execute a shell command (generated by LLM) with allowlist validation.

    Security layers:
    1. Only command field is used — text field is NEVER executed (injection vector).
    2. Shell operators (|, ;, &, >, <, $, `, \\) are always rejected.
    3. First token must be in SAFE_BINARIES allowlist.
    4. rm has extra restrictions: -rf, -fr are blocked.
    5. shlex.split() without shell mode prevents injection.
    """
    command_str = intent.entities.get("command", "")
    # SECURITY: NEVER fall back to text field — it's for ask/web_search queries,
    # not executable commands. This prevents the LLM from putting arbitrary
    # content in text that gets silently executed as a shell command.
    if not command_str:
        return ActionResult(ok=False, spoken="No pude entender el comando, señor.")

    # Block shell operators — prevents injection like "ls; rm -rf /"
    if _SHELL_OPERATORS.search(command_str):
        return ActionResult(ok=False, spoken="Lo lamento, señor, ese comando no es seguro.")

    # Parse command safely via shlex (list-args, no shell)
    try:
        command = shlex.split(command_str)
    except ValueError as exc:
        return ActionResult(ok=False, spoken=f"El comando no es válido, señor: {exc}")

    if not command:
        return ActionResult(ok=False, spoken="No pude entender el comando, señor.")

    binary = command[0]

    # Allowlist: first token must be a known-safe binary
    if binary not in SAFE_BINARIES:
        return ActionResult(ok=False, spoken=f"No tengo permiso para ejecutar '{binary}', señor.")

    # Extra rm restrictions: block -rf, -fr combinations
    if binary == "rm" and _RM_DANGEROUS.search(command_str):
        return ActionResult(ok=False, spoken="Lo lamento, señor, no puedo borrar con -rf.")

    base.log(f"execute: {command_str}")
    code, output = base.safe_run(command)

    if code != 0:
        # Show brief error to user
        error_msg = output.strip()[:100] if output else f"código de salida {code}"
        return ActionResult(ok=False, spoken=f"El comando falló, señor: {error_msg}")

    # Brief success — don't dump full output via TTS
    return ActionResult(ok=True, spoken="Listo, comando ejecutado, señor.")
