"""System executor (PR4, task 4.4): shutdown/reboot via systemctl, open_app allowlisted, execute arbitrary commands.

Design (RF-8, threat matrix): destructive actions run behind the orchestrator's
15s confirm gate and are logged here; open_app only ever spawns xdg-open with
an allowlisted app (disallowed app => rejected, nothing spawned). The execute
intent runs arbitrary shell commands with confirmation (Option A) or auto
(Option B via AUTO_EXECUTE config).
"""

from __future__ import annotations

import shlex

from jarvis import config
from jarvis.actions import base
from jarvis.interpreter import schema
from jarvis.interpreter.schema import Intent
from jarvis.orchestrator.contracts import ActionResult

# User-friendly names → actual command/bin names.
# xdg-open only works with .desktop files or URLs, not app aliases.
_APP_COMMANDS: dict[str, str] = {
    "terminal": "gnome-terminal",
    "explorador": "nemo",
    "navegador": "firefox",
    "nemo": "nemo",
    "nautilus": "nautilus",
    "libreoffice": "libreoffice",
    "code": "code",
    "codium": "codium",
    "vim": "gnome-terminal",
    "nano": "gnome-terminal",
    "htop": "gnome-terminal",
    "opencode": "opencode",
    "spotify": "spotify",
}


def _run(name: str, command: list[str], ok_spoken: str, fail_spoken: str) -> ActionResult:
    base.log(name)
    code, _ = base.safe_run(command)
    if code != 0:
        return ActionResult(ok=False, spoken=fail_spoken)
    return ActionResult(ok=True, spoken=ok_spoken)


def shutdown(intent: Intent, session: object) -> ActionResult:
    return _run("shutdown", ["systemctl", "poweroff"], "Apagando el sistema, señor.", "Lo lamento, señor, no pude apagar el sistema.")


def reboot(intent: Intent, session: object) -> ActionResult:
    return _run("reboot", ["systemctl", "reboot"], "Reiniciando el sistema, señor.", "Lo lamento, señor, no pude reiniciar el sistema.")


def open_app(intent: Intent, session: object) -> ActionResult:
    app = intent.entities.get("app", "")
    if schema.validate_entities(intent, config.ALLOWED_APPS):
        return ActionResult(ok=False, spoken="Esa aplicación no está permitida, señor.")
    # Resolve friendly name to actual command
    command = _APP_COMMANDS.get(app, app)
    code, _ = base.safe_run([command])
    if code != 0:
        return ActionResult(ok=False, spoken="Lo lamento, señor, no pude abrir esa aplicación.")
    return ActionResult(ok=True, spoken=f"Abriendo {app}, señor.")


def execute(intent: Intent, session: object) -> ActionResult:
    """Execute an arbitrary shell command (generated by Ollama).

    Option A (AUTO_EXECUTE=False): confirmation happens in the orchestrator
    before this is called, so we just run it.
    Option B (AUTO_EXECUTE=True): called directly, no confirmation.
    """
    command_str = intent.entities.get("command", "")
    # Fallback: if command is empty, try text field (LLM sometimes puts it there)
    if not command_str:
        command_str = intent.entities.get("text", "")
    if not command_str:
        return ActionResult(ok=False, spoken="No pude entender el comando, señor.")

    # Safety: basic blocklist for catastrophic commands
    import re
    if re.search(r'\brm\s+(-[a-zA-Z]*f[a-zA-Z]*\s+/*|/\*)', command_str):
        return ActionResult(ok=False, spoken="Lo lamento, señor, ese comando es demasiado peligroso.")

    # Parse command safely via shlex (list-args, no shell)
    try:
        command = shlex.split(command_str)
    except ValueError as exc:
        return ActionResult(ok=False, spoken=f"El comando no es válido, señor: {exc}")

    if not command:
        return ActionResult(ok=False, spoken="No pude entender el comando, señor.")

    base.log(f"execute: {command_str}")
    code, output = base.safe_run(command)

    if code != 0:
        # Show brief error to user
        error_msg = output.strip()[:100] if output else f"código de salida {code}"
        return ActionResult(ok=False, spoken=f"El comando falló, señor: {error_msg}")

    # Brief success — don't dump full output via TTS
    return ActionResult(ok=True, spoken="Listo, comando ejecutado, señor.")
